### ISSUE TITLE
Can this LpCVT executable achieve triangle mesh generation with sharp feature preservation?

### ISSUE THREAD

**Issue by mo1shang** [secantalpha/LpCVT#1]
The LpCVT paper claims that it can generate good triangular mesh while maintaining sharp features, but the example three-hole mesh file in the LpCVT program does not have sharp features, and I wonder if LpCVT can maintain sharp features, as the paper says. I thought about testing LpCVT, but LpCVT requires two input files, so I couldn't simply input a mesh file with sharp features to test.

**Comment by museova** [comment]
Of course, but some modifications to the source code are required. You can refer to this  [paper](https://arxiv.org/pdf/2404.15661)

**Comment by mo1shang** [comment]
Thank you so much for your reply.
